openapi: 3.0.1
info:
  title: Star Wars
  description: ''
  version: v2
servers:
  - url: https://apim-ent-snbx-iyy37277.azure-api.net/sw/v2
paths:
  /people/:
    get:
      summary: Get People
      description: Get People
      operationId: get-people
      responses:
        '200':
          description: ''
  /film:
    get:
      summary: Get Film
      description: Get Film
      operationId: get-film
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                count: 1
                films:
                  - title: A New Hope
                    release-date: '1977-05-25T00:00:00.0000000+00:00'
  '/people/{id}/':
    get:
      summary: Get People By Id
      description: Get People By Id
      operationId: get-people-by-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]